version: 2

models:
  - name: dim_employer
    description: Employer dimension (organization + workplace attributes).
    columns:
      - name: employer_id
        tests: [not_null, unique]
      - name: employer_name
      - name: employer_workplace
      - name: employer_organization_number

  - name: dim_occupation
    description: Occupation dimension derived from job ads occupation labels.
    columns:
      - name: occupation_id
        tests: [not_null, unique]
      - name: occupation
        tests: [not_null]
      - name: occupation_group
        tests: [not_null]
      - name: occupation_field
        tests: [not_null]

  - name: dim_job_details
    description: Job details dimension with textual and numeric job attributes.
    columns:
      - name: job_details_id
        tests: [not_null, unique]
      - name: headline
        tests: [not_null]
      - name: description
        tests: [not_null]
      - name: description_html_formatted
        tests: [not_null]
      - name: employment_type
        tests: [not_null]
      - name: duration
        tests: [not_null]
      - name: salary_type
        tests: [not_null]
      - name: scope_of_work_min
        tests: [not_null]
      - name: scope_of_work_max
        tests: [not_null]

  - name: dim_auxilliary_attributes
    description: Auxilliary requirement attributes for job ads (experience, license, car access).
    columns:
      - name: auxilliary_attributes_id
        tests: [not_null, unique]
      - name: experience_required
        tests: [not_null]
      - name: driver_license
        tests: [not_null]
      - name: access_to_own_car
        tests: [not_null]