USE ROLE ACCOUNTADMIN;
SHOW ROLES;

USE ROLE job_ads_dlt_role;

USE SCHEMA job_ads.staging;

SHOW TABLES;

DESC TABLE job_ads;

USE WAREHOUSE compute_wh;

-- SELECT * FROM job_ads;

SELECT
    RELEVANCE,
    WORKPLACE_ADDRESS__STREET_ADDRESS,
    WORKPLACE_ADDRESS__POSTCODE,
    PUBLICATION_DATE,
    WEBPAGE_URL,
    SOURCE_TYPE,
    TIMESTAMP,
    TO_CHAR(TO_TIMESTAMP(timestamp / 1000), 'YYYY-MM-DD HH24:MI:SS')
        AS readable_timestamp
FROM job_ads LIMIT 5;

SELECT
    SCOPE_OF_WORK__MIN,
    SCOPE_OF_WORK__MAX,
    EMPLOYER__NAME,
    SALARY_TYPE__LABEL,
    SALARY_DESCRIPTION,
    DURATION__LABEL,
    LOGO_URL,
    EMPLOYER__WORKPLACE,
    EMPLOYER__NAME,
    EMPLOYER__URL
FROM job_ads LIMIT 5;

SELECT DISTINCT SALARY_DESCRIPTION FROM job_ads;