SHOW DATABASES;

USE DATABASE FREE_GLOBAL_B2B_COMPANY_AND_BUSINESS_PERSON_DATA_WITHOUT_PII;

SHOW SCHEMAS;

USE SCHEMA REVENUEBASE_FREE_DATA;

SHOW TABLES;

SHOW VIEWS;

SELECT * FROM COMPANIES_FREE LIMIT 5;

DESC VIEW COMPANIES_FREE;

SELECT COUNT(*) AS number_rows FROM COMPANIES_FREE;

SELECT DISTINCT COMPANY_ENTITY_TYPE FROM COMPANIES_FREE;

-- check number unique names
SELECT COUNT(DISTINCT COMPANY_NAME) AS number_unique_names
FROM COMPANIES_FREE LIMIT 5;

-- check unique countries
SELECT COUNT(DISTINCT LOCATION_COUNTRY_CODE) FROM COMPANIES_FREE;

-- check number of companies in different countries
SELECT
    LOCATION_COUNTRY_CODE,
    COUNT(*) AS number_organizations
FROM COMPANIES_FREE
GROUP BY LOCATION_COUNTRY_CODE
ORDER BY number_organizations DESC;

-- check organizations in nordic countries 
SELECT
    LOCATION_COUNTRY_CODE,
    COUNT(*) AS number_organizations
FROM COMPANIES_FREE
GROUP BY LOCATION_COUNTRY_CODE
HAVING LOCATION_COUNTRY_CODE IN ('SE', 'DK', 'NO', 'FI', 'IS') -- where clause cannot be used with aggregate functions
ORDER BY number_organizations DESC;

-- check organizations in regions in nordic countries
SELECT
    LOCATION_COUNTRY_CODE,
    LOCATION_COUNTRY_REGION,
    COUNT(*) AS number_organizations
FROM COMPANIES_FREE
GROUP BY LOCATION_COUNTRY_CODE, LOCATION_COUNTRY_REGION
HAVING LOCATION_COUNTRY_CODE IN ('SE', 'DK', 'NO', 'FI', 'IS')
ORDER BY number_organizations DESC;